### ISSUE TITLE
This is not working with Ubuntu 18.04 and it's showing there is no release is available.

### ISSUE THREAD

**Issue by 2daygeek** [TurboLabIt/zzupdate#1]
This is not working with Ubuntu 18.04 and it's showing there is no release is available.

**Comment by 2daygeek** [comment]
I have fixed the issue by updating the release upgrade command

From

 do-release-upgrade

To 

 do-release-upgrade -d

Please update the script accordingly and we will publish the article shortly in our website.

**Comment by ZaneCEO** [comment]
Sorry for the delay. Won't do [because](https://help.ubuntu.com/lts/serverguide/installing-upgrading.html.en)...

> It is also possible to use do-release-upgrade to upgrade to a development version of Ubuntu. To accomplish this use the -d switch:
> 
> do-release-upgrade -d
> Upgrading to a development release is not recommended for production environments.

If the tool can't find a new release, it means it was not pushed on the stable channel yet. Retry in a few hours.
